#!/usr/bin/env python3

# This script runs the executable "unitTests" repeatedly, for various numbers of MPI processes.
# The executable "unitTests" is created by running "make unitTests" from the main qsc directory.

import subprocess
import sys
import os

max_N_procs = 1

#####################################################################
# Make sure unitTests exists
#####################################################################

if os.path.isfile("unitTests"):
    testfile = "unitTests"
elif os.path.isfile("unitTests_single"):
    testfile = "unitTests_single"
else:
    print("The executable `unitTests' does not appear to be present in the qsc/tests/ directory")
    print("You need to run `make unitTests' from the QSC build directory to build the unitTests executable.")
    exit(1)

#####################################################################
# Get QSC_COMMAND_TO_SUBMIT_JOB
#####################################################################

filename = "commandToSubmitJob"
try:
    f = open(filename,"r")
except:
    print("Error! Unable to open the file "+filename+" in the tests directory.")
    exit(1)
submitCommand = f.read()
f.close()

print("QSC_COMMAND_TO_SUBMIT_JOB=",submitCommand)

#####################################################################
# Loop over N_procs, calling unitTests each time
#####################################################################

all_succeeded = True
for N_procs in range(1, max_N_procs+1):
    command = submitCommand + " ./" + testfile
    command = command.replace('NUM_PROCS',str(N_procs))
    print("Submitting command "+command)
    sys.stdout.flush()
    exit_code = subprocess.call(command.split())
    print("exit code: ",exit_code)
    if exit_code != 0:
        all_succeeded = False

if all_succeeded:
    print("Unit tests pass for all values of N_procs.")
else:
    print("!!! Unit tests did not all pass !!!")
    exit(1)
