#!/bin/bash

# This script is meant to be run from the "tests" directory of qsc.

set -ex
# In the above line, "set -e" causes this script to exit as soon as any line fails. "set -x" causes each line of this script to be printed (with a + in front) before it is executed, so if a step fails, you can see from the log what command failed.

echo Running all tests

./runMPIUnitTests