#!/bin/bash

# This script runs the examples. It is used in the Github Actions continuous integration.

set -ex

XQSC=../bin/xqsc

$XQSC qsc_in.single_LandremanSenguptaPlunk_section5.1
$XQSC qsc_in.single_LandremanSengupta2019_section5.1
$XQSC qsc_in.single_LandremanSengupta2019_section5.2

$XQSC qsc_in.opt_QH_nfp4

$XQSC qsc_in.multiopt_QH_nfp4
$XQSC qsc_in.multiopt_QH_nfp4_well
$XQSC qsc_in.multiopt_QA_nfp2

$XQSC qsc_in.random_scan_small
$XQSC qsc_in.random_scan_realistic
mpiexec -n 2 $XQSC qsc_in.random_scan_small
mpiexec -n 2 $XQSC qsc_in.random_scan_realistic
